### ISSUE TITLE
Python 2.6 incompatibility

### ISSUE THREAD

**Issue by johanfforsberg** [pjkundert/cpppo#2]
I tried installing cppio under Python 2.6 (CentOS 6) and I got this error:

```
Downloading/unpacking cpppo
  Downloading cpppo-2.9.1.tar.gz (202kB): 202kB downloaded
  Running setup.py egg_info for package cpppo
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip-build-johfor/cpppo/setup.py", line 14, in <module>
        if sys.version_info.major < 3:
    AttributeError: 'tuple' object has no attribute 'major'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip-build-johfor/cpppo/setup.py", line 14, in <module>

    if sys.version_info.major < 3:

AttributeError: 'tuple' object has no attribute 'major'
```

This is apparently only supported in >=2.7. I have no idea if there are other things preventing cpppo from working on 2.6, but at least it's a good idea to state somewhere that it's only compatible with 2.7 and up.
